# Generated by Django 5.2.7 on 2025-11-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=500)),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'alert_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('analytics_type', models.CharField(choices=[('price_stats', 'Price Statistics'), ('z_score', 'Z-Score'), ('spread', 'Spread'), ('hedge_ratio', 'Hedge Ratio'), ('correlation', 'Rolling Correlation'), ('adf_test', 'ADF Test')], db_index=True, max_length=20)),
                ('timeframe', models.CharField(db_index=True, default='tick', max_length=5)),
                ('window_size', models.IntegerField(default=100)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField()),
            ],
            options={
                'db_table': 'analytics_cache',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['symbol', 'analytics_type', 'timeframe'], name='analytics_c_symbol_3e6165_idx')],
            },
        ),
    ]
